### ISSUE TITLE
Please share the SDK of V2

### ISSUE THREAD

**Issue by saqarmax-arm** [pancakeswap/pancakeswap-sdk-v1#9]
I am unable to use the old sdk with new factory address. And there is no documentation to be found for that. 
Can  you please share v2 sdk?

**Comment by pseudonymus** [comment]
@saqarmax-arm This one should be it https://www.npmjs.com/package/@pancakeswap-libs/sdk-v2

**Comment by ChefKai** [comment]
Hello, SDK v2 has been released; you can find it here:
- GitHub: https://github.com/pancakeswap/pancakeswap-sdk-v2
- NPM: https://www.npmjs.com/package/@pancakeswap-libs/sdk-v2
